---
- name: 判断项目下是否存在edu.warbak备份文件
  stat: path={{ tomcat_dir }}/webapps/{{ project_name }}.warbak
  register: bak_existed

- name: 如果备份文件不存在中断操作
  fail:
    msg: "edu.warbak文件不存在，无法回滚"
  when: bak_existed.stat.exists == false

- name: 关闭tomcat服务
  shell: ps -ef | grep /usr/local/apache-tomcat-7.0.85 | grep -v grep |awk '{print $2}'| xargs kill -9

- name: 验证tomcat是否关闭成功
  wait_for:
    port=8080
    state=stopped
    timeout=3

- name: 判断当前环境下是否有edu项目
  stat:
    path={{ tomcat_dir }}/webapps/{{ project_name }}
  register: edu_existed

- name: edu项目存在则删除
  file:
    path: "{{ tomcat_dir }}/webapps/{{ project_name }}"
    state: absent
  when: edu_existed.stat.isdir is defined and edu_existed.stat.isdir

- name: 判断项目下是否存在edu.war文件
  stat: path={{ tomcat_dir }}/webapps/{{ project_name }}.war
  register: war_existed

- name: edu.war包文件存在则删除
  file:
    path: "{{ tomcat_dir }}/webapps/{{ project_name }}.war"
    state: absent
  when: war_existed.stat.exists == true

- name: 从edu.warbak文件恢复war包
  shell: mv {{ tomcat_dir }}/webapps/{{ project_name }}.{warbak,war}
  when: bak_existed.stat.exists == true

- name: 启动tomcat
  shell: nohup {{ tomcat_dir }}/bin/startup.sh

- name: 验证tomcat是否启动成功
  wait_for:
    port=8080
    state=started
    delay=20
    timeout=30
