---
- hosts: edu
  gather_facts: false
  roles:
    - { role: deploy, tags: ["deploy"] }
    - { role: rollback, tags: ["rollback"] }

- hosts: backup
  gather_facts: false
  roles:
    - { role: packaging, tags: ["packaging"] }

- hosts: localhost
  gather_facts: false
  roles:
    - { role: mvn, tags: ["mvn"] }
